### ISSUE TITLE
[Chore] 프로젝트 세팅

### ISSUE THREAD

**Issue by binisnil** [DO-SOPT-iOS-Part/ParkYunBin-assignment#1]
## PREVIEW 🔭

> 과제를 위한 프로젝트를 세팅합니다

## TO-DO 📒

- [x] 코드베이스로 세팅
- [x] 이슈 템플릿 생성
- [x] PR 템플릿 생성
- [x] 폰트 추가
- [x] Snapkit 설치
- [x] then 설치
- [x] 폴더링
- [x] 이미지 에셋 추가
- [x] 이미지 리터럴 정리
