### ISSUE TITLE
[Feat] 3주차 과제

### ISSUE THREAD

**Issue by binisnil** [DO-SOPT-iOS-Part/ParkYunBin-assignment#5]
## 🖌️ DESCRIBE
 > 3주차 심화과제를 진행합니다

##  🔖 TODO-LIST
- [ ] UIPageControl() 추가
- [ ] 일기예보 더미데이터 생성
- [ ] 일기예보 TableView UI 구현
- [ ] TableView 더미데이터 기반으로 생성
- [ ] TableView 접히도록 구현
- [ ] ProgressBar 그라디언트 구현
